---
- hosts: local
  gather_facts: false

  vars_files:
    - ./vars/vars.yml

  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes

  tasks:

    - name: Destroy the container
      lxc_container:
        name: "{{vm_name}}"
        container_log: true
        template: download
        state: absent
      become: true
      tags:
        - destroy

    - name: Add new entry of the container in local /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: "{{vm_name}}$"
        state: absent
      become: true
      tags: [destroy]

    - name: Delete the entry from ./created_vms_list.md
      lineinfile:
        dest: ./created_vms_list.md
        regexp: '^\|{{vm_name}}'
        state: absent
      tags: [destroy]
