---
- hosts: local
  gather_facts: false

  vars_files:
    - ./vars/vars.yml

  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes

  tasks:
#    - name: Create a ansible-ubuntu-bionic container
#      lxc_container:
#        name: ansible-ubuntu-bionic
#        container_log: true
#        template: download
#        state: stopped
#        template_options: --dist ubuntu --release bionic --arch amd64
#        lxc_path: /var/lib/lxc
#      become: true

    - name: Create or start {{vm_name}} container
      lxc_container:
        name: "{{vm_name}}"
        container_log: true
        template: download
        state: started
        template_options: --dist centos --release 7 --arch amd64
        lxc_path: /var/lib/lxc
        container_command: |
          > /etc/hosts
          cat <<EOF | tee -a /etc/hosts
          {{vm_ip}} localhost
          {{vm_ip}} {{vm_name}}
          {{vm_ip}} hostname
          EOF
          yum -y install net-tools
          ifconfig eth0 {{vm_ip}} netmask 255.255.255.0
          service network restart
          yum -y install openssh-server
          service sshd start
          useradd admin
          echo "admin:admin" | chpasswd
          mkdir /home/admin/.ssh
          echo {{vm_admin_ssh_authorized_key}} > /home/admin/.ssh/authorized_keys
          chown -R admin:admin /home/admin/.ssh
          chmod 700 /home/admin/.ssh
          chmod 600 /home/admin/.ssh/authorized_keys
#        container_config:
      become: true

    - name: Add new entry in local /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{vm_ip}} {{vm_name}}"
        state: present
      become: true


