---
- hosts: local
  gather_facts: false

  vars_files:
    - ./vars/vars.yml

  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes

  tasks:

    - name: Stop {{vm_name}} container
      lxc_container:
        name: "{{vm_name}}"
        container_log: true
        state: stopped
      become: true
